on:
  push:
    branches:
      - v4
name: release-please
permissions:
  contents: write
  pull-requests: write
  packages: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-go@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: "^1.26"
          cache-dependency-path: core/go.sum

      - name: Release Note
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
